name: Release to Maven Central

on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: maven-central
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17 with GPG and OSSRH
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: 'ossrh'
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Show Maven version
        run: mvn -v

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                    http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>ossrh</id>
                <username>\${env.OSSRH_USERNAME}</username>
                <password>\${env.OSSRH_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy core modules to OSSRH
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn -B -ntp -DskipTests \
            -Dmaven.deploy.skip=false \
            -Dgpg.passphrase="${GPG_PASSPHRASE}" \
            -pl core,annotations,processor -am deploy

      # Optionally close and release staging repository (requires proper plugin configuration)
      # - name: Close and release staging repository
      #   env:
      #     OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      #     OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      #   run: |
      #     mvn -B -ntp \
      #       -pl core,annotations,processor -am \
      #       nexus-staging:release


